### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mcfd** [werererer/japokwm#13]
When I play minecraft, my mouse cursor is not captured by the game, it is captured by wm.

**Comment by werererer** [comment]
thanks for the info. Do you know if this bug accours in all games or is it only limited to minecraft?

**Comment by werererer** [comment]
Sorry for taking so long but I finally found the time to look into this bug and can reproduce it. (I was busy implementing some features xD). I will fix it with the next release of japokwm (0.3) when it is ready in a few weeks. (active development of 0.3 happens currently on the development branch to ensure somewhat of stability in master)

**Comment by werererer** [comment]
I think I fixed it now. It should work now the development branch. Be aware that the development branch is considered unstable.
