### ISSUE TITLE
Implement wlroots scene api

### ISSUE THREAD

**Issue by werererer** [werererer/japokwm#36]
This is better than the stuff I hacked together and will fix the issue #34 automatically while reducing LOC and automatically fixing bugs.

**Comment by werererer** [comment]
@Magnitudexx I opened 3 new branches. wlr_scene and wlr_scene_xdg, wlr_scene_layer_shell. If you want to work on wlr_scene_xdg then start in wlr_scene_xdg and we will merge that later into wlr_scene. I would prefer if you'd try to make xdg_surfaces work well with wlr_scene :).

**Comment by werererer** [comment]
If you need some advice how to continue work/want to do something else/or what a struct does just write it here it I will fix my notifications.

**Comment by werererer** [comment]
@Magnitudexx I think I will do that one alone :). I messed around with the wlr_scene api a bit and it is so amazing and simple that I can do it myself.
If you want to help this project in another way directly you can try messing around with the lua api and find issues in regards to crashes and documentation. Or if you know some ipc simplifying the code of japokmsg would also help.

**Comment by Magnitudexx** [comment]
Sounds good, right now my life is hectic so maybe i wont have time to contribute but I can definitely try running stuff to see if it works as soon as Christmas is over.

**Comment by werererer** [comment]
wlr_scene seems to be too simple for my usecase. Some things seem to be impossible to implement there. I will drop that idea. That means we need to reopen #34 again.
