### ISSUE TITLE
Release of 0.4

### ISSUE THREAD

**Issue by werererer** [werererer/japokwm#41]
0.4 will be released on Wednesday or Friday. There are still 2 issues to solve till the release though:

- [x] Fix the aur package
- [x] Fix issues related to multimonitor (focus)

Every other issue will be postponed to after 0.4

**Comment by Magnitudexx** [comment]
May I suggest something? It would be really nice to have a discord or IRC where we could discuss things not touched on by PMs or issues

**Comment by werererer** [comment]
yeah you are right. I will open one.

**Comment by werererer** [comment]
@Magnitudexx I added one here: https://webchat.freenode.net/#japokwm You can also find the link in the new readme at development.

**Comment by werererer** [comment]
Forget the irc let's use discord instead. This is the new link: https://discord.gg/WpGjAU393M.

**Comment by werererer** [comment]
Release is today evening. I only have to write the release changelog and then we are good to go.
