### ISSUE TITLE
Action.exec spawns zombie processes

### ISSUE THREAD

**Issue by manfred3000** [werererer/japokwm#52]
OS: Arch Linux
Japokwm: 0.4.0 (AUR)

Applications launched from `init.lua` via keybinding will become zombies of their parent `japokwm` after termination.

**Comment by werererer** [comment]
ok I will investigate that issue thanks for reporting.

**Comment by werererer** [comment]
ok I think I fixed it. This issue will probably be fix with v0.4.1 in the future or you can start using the development version now :)(you have to manually compile for that though).
